platform_main/urls.py
from django.urls import path
from platform_main.views.user import *
from platform_main.views.admin import *
from platform_main.views.integration import *
from platform_main.views.user.campaigns import get_statistic, get_min_price
from platform_main.views.user.register import ChangePassword
from platform_main.views.user.login import home_redirect

urlpatterns = [
    # User
    path('', home_redirect, name='start'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('home/', HomeView.as_view(), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('campaigns/create/', CreateCampaignView.as_view(), name='campaigns_create'),
    path('campaigns/list/', ListCampaignsView.as_view(), name='campaigns_list'),
    path('campaigns/<int:campaign_id>/statistics', CampaignStatistics.as_view(), name='campaigns_statistics'),
    path('campaigns/<int:pk>/delete', DeleteCampaign.as_view(), name='campaigns_delete'),
    path('campaigns/<int:pk>/update', UpdateCampaign.as_view(), name='campaigns_update'),
    path('campaigns/<int:campaign_id>/<str:action>', CampaignAction.as_view(), name='campaigns_action'),
    path('campaigns/create/get_min_price', get_min_price),
    path('invoices/list', ListInvoices.as_view(), name='user_invoices_list'),
    path('invoices/create', CreateInvoice.as_view(), name='user_invoice_create'),
    path('invoices/download/<int:invoice_id>', DownloadInvoice.as_view(), name='user_invoice_download'),

    path('total_statistics', AllStatistics.as_view(), name='total_statistics'),
    path('get_statistic', get_statistic, name='get_statistic'),
    # Admin
    path('admin/login/', AdminLoginView.as_view(), name='admin_login'),
    path('admin/statistics/', AllStatistics.as_view(), name='admin_total_statistics'),

    # Campaigns
    path('admin/campaigns/<int:campaign_id>/delete/', AdminDeleteCampaignView.as_view(), name='admin_campaign_delete'),
    path('admin/campaigns/list/', AdminCampaignsView.as_view(), name='admin_campaigns_list'),
    path('admin/campaigns/', AdminCreateCampaignView.as_view(), name='admin_campaign_create'),
    path('admin/home/', AdminHomeView.as_view(), name='admin_home'),
    path('admin/campaigns/<int:campaign_id>', AdminCampaign.as_view(), name='admin_campaign'),
    path('admin/campaigns/<int:campaign_id>/update', AdminCampaignUpdate.as_view(), name='admin_campaign_update'),
    path('admin/campaigns/<int:campaign_id>/start',
         AdminCampaignAction.as_view(action="start"),
         name='admin_campaign_action_start'),
    path('admin/campaigns/<int:campaign_id>/stop',
         AdminCampaignAction.as_view(action="stop"),
         name='admin_campaign_action_stop'),

    # Accounts
    path('admin/accounts/list/', AdminAccountsView.as_view(), name='admin_accounts_list'),
    path('admin/accounts/delete/<int:account_id>', AdminDeleteAccountView.as_view(), name='admin_account_delete'),
    path('admin/accounts/<int:account_id>', AdminAccountView.as_view(), name='admin_account'),
    path('admin/accounts/<int:account_id>/stop', AdminStopAccount.as_view(), name='admin_account_stop'),

    # Sources
    path('admin/sources', AdminSourcesView.as_view(), name='admin_sources_list'),
    path('admin/click_prices', AdminSourcesPriceView.as_view(), name='admin_sources_prices'),
    path('admin/sources_prices/create', AdminCreateSourcePrice.as_view(), name='admin_sources_prices_create'),
    path('admin/sources_prices/<int:source_price>/update',
         AdminSourcesUpdate.as_view(),
         name='admin_update_source_price'),
    path('admin/sources_prices/<int:pk>/delete',
         AdminDeleteSourcePrice.as_view(),
         name='admin_delete_source_price'),
    path('admin/sources/create', AdminCreateSource.as_view(), name='admin_create_source'),
    path('admin/sources/<int:pk>/edit', AdminUpdateSource.as_view(), name='admin_update_source'),
    path('admin/sources/<int:pk>/delete', AdminDeleteSource.as_view(), name='admin_delete_source'),

    # Invoices
    path('admin/invoices/<int:pk>/delete', AdminInvoiceDelete.as_view(), name='admin_delete_invoice'),
    path('admin/invoices/<int:pk>/accept', AdminInvoiceAccept.as_view(), name='admin_accept_invoice'),
    path('admin/invoices/list/', AdminListInvoices.as_view(), name='admin_list_invoices'),
    path('admin/invoices/<int:pk>/download', AdminDownloadInvoice.as_view(), name='admin_download_invoice'),

    # Integration
    path('integrations/campaigns', ActiveCampaigns.as_view(), name='integrations_list_campaigns'),
    path('change_password/', ChangePassword.as_view())

]

redirectplatform/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    re_path('', include(('platform_main.urls', 'platform_main'), namespace='platform_main')),
    path('admin/su35', admin.site.urls),
]

platform_main/models/campaign.py
from django.db import models
from django.db.models import OuterRef, F, Sum, ExpressionWrapper, Value, Min
from django.db.models.functions import Coalesce
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.postgres.fields import ArrayField
from django import forms

from platform_main.models.enums import Geo, EmailType, OperationalSystem, Platform, Format
from utils.models import ModelEnhanced


class ChoiceArrayField(ArrayField):
    """
    A field that allows us to store an array of choices.

    Uses Django 1.9's postgres ArrayField
    and a MultipleChoiceField for its formfield.

    Usage:

        choices = ChoiceArrayField(models.CharField(max_length=...,
                                                    choices=(...,)),
                                   default=[...])
    """

    def formfield(self, **kwargs):
        defaults = {
            'form_class': forms.MultipleChoiceField,
            'choices': self.base_field.choices,
        }
        defaults.update(kwargs)
        # Skip our parent's formfield implementation completely as we don't
        # care for it.
        # pylint:disable=bad-super-call
        return super(ArrayField, self).formfield(**defaults)


class Status(models.TextChoices):
    RUNNING = 'running', _('Running')
    STOPPED = 'stopped', _('Stopped')


class FutureStatuses(models.TextChoices):
    REQUEST_STOP = 'stop_requested', _("Stop requested")
    REQUEST_RUN = 'run_requested', _("Run requested")


FutureStatusesMapping = {
    FutureStatuses.REQUEST_STOP.value: Status.STOPPED.value,
    FutureStatuses.REQUEST_RUN.value: Status.RUNNING.value
}


class Source(ModelEnhanced):
    name = models.CharField(max_length=20)
    system_id = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class SourcePrice(ModelEnhanced):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    type = models.CharField(choices=EmailType.choices)
    format = models.CharField(choices=Format.choices)
    platform = models.CharField(choices=Platform.choices)
    geo = models.CharField(choices=Geo.choices)
    price = models.DecimalField(max_digits=10, decimal_places=4)

    @classmethod
    def get_unique_values(cls, filter_data: dict):
        return cls.objects.all().filter(**filter_data) \
            .order_by() \
            .values('source', 'type', 'format', 'platform', 'geo')

    @classmethod
    def get_min_price(cls, filter_data: dict):
        res = cls.objects.all().filter(**filter_data).aggregate(min_price=Min('price'))
        return res.get('min_price', 0)


class CustomCampaignManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)

    def get_sources_statistics(self):
        subquery_utils = {k: OuterRef(k) for k in ['format', 'type', 'geo', 'os', 'platform', 'source']}
        subquery_running = self.get_queryset() \
            .filter(current_status=Status.RUNNING.value, **subquery_utils) \
            .values('format', 'type', 'geo', 'platform', 'source') \
            .annotate(total_clicks=Sum('clicks_per_day', default=0)) \
            .values('total_clicks')
        subquery_waiting_for_moderation = self.get_queryset() \
            .filter(current_status=Status.STOPPED.value, next_status__isnull=False, **subquery_utils) \
            .values('format', 'type', 'geo', 'platform', 'source') \
            .annotate(total_clicks=Sum('clicks_per_day', default=0)) \
            .values('total_clicks')
        res = self.get_queryset().values('format', 'type', 'geo', 'platform', 'source__id', 'source__name') \
            .annotate(current=Coalesce(subquery_running, Value(0))) \
            .annotate(future=Coalesce(subquery_waiting_for_moderation, F('current'))) \
            .annotate(delta=ExpressionWrapper(F('future') - F('current'), output_field=models.IntegerField()))
        res = res.distinct()
        return res


class Campaign(ModelEnhanced):
    name = models.CharField(max_length=250)
    type = models.CharField(choices=EmailType.choices)
    format = models.CharField(choices=Format.choices)
    link = models.CharField(max_length=250)
    platform = models.CharField(choices=Platform.choices)
    os = ChoiceArrayField(base_field=models.CharField(choices=OperationalSystem.choices, max_length=20), null=False)
    geo = models.CharField(choices=Geo.choices)
    price = models.DecimalField(max_digits=10, decimal_places=4)
    # daily_budget = models.IntegerField(null=True)
    clicks_per_day = models.IntegerField()
    user = models.ForeignKey('platform_main.User', on_delete=models.SET_NULL, related_name='campaigns', null=True)
    current_status = models.CharField(choices=Status.choices, default=Status.STOPPED)
    next_status = models.CharField(choices=FutureStatuses.choices, null=True)
    is_deleted = models.BooleanField(default=False)
    source = models.ForeignKey('platform_main.Source', on_delete=models.PROTECT)

    @property
    def os_display(self):
        return ', '.join([str(OperationalSystem(_os).label) for _os in self.os])

    def moderation_decision(self, action: str):
        if action == 'start':
            next_status = Status.RUNNING.value
        elif action == 'stop':
            next_status = Status.STOPPED.value
        else:
            raise Exception
        self.next_status = None
        self.current_status = next_status
        self.save(update_fields=['current_status', 'next_status'])

    def user_action(self, action: FutureStatuses):
        next_status = FutureStatusesMapping.get(action.value)
        if next_status == self.current_status:
            self.next_status = None
            self.save(update_fields=['next_status'])
        else:
            self.next_status = action.value
            self.save(update_fields=['next_status'])

    def delete(self, *args, **kwargs):
        self.is_deleted = True
        self.save(update_fields=['is_deleted'])

    @property
    def get_css_class(self):
        match self.current_status:
            case "running":
                return "start"
            case "stopped":
                return "stop"

    @property
    def get_button_src(self):
        match self.current_status:
            case "running":
                return f"admin/campaigns/stop.svg"
            case "stopped":
                return f"admin/campaigns/start.svg"

    @property
    def clicks_today(self) -> int:
        try:
            clicks = self.clicks_set.all().get(at=timezone.now().replace(minute=0, second=0, microsecond=0))
            return clicks.clicks
        except ObjectDoesNotExist:
            return 0

    objects = CustomCampaignManager()

platform_main/models/invoices.py
from datetime import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


class InvoiceTypes(models.TextChoices):
    BANK = 'bank', _("Bank")
    CAPITALIST = 'capitalist', _("Capitalist")
    USDT = 'usdt', _("USDT")


def build_invoice(d: list, number, email, amount, invoice_type, created_at: datetime):
    d.append(Paragraph('INVOICE'))
    d.append(Paragraph(f'# {number}'))
    d.append(Spacer(1, 20))
    d.append(Paragraph('Agatix Story Limited'))
    d.append(Paragraph('Bank: STANDARD CHARTERED BANK (HONG KONG)'))
    d.append(Paragraph('SWIFT: SCBLHKHH'))
    d.append(Paragraph(f'Date: {created_at.strftime("%d.%m.%Y")}'))
    d.append(Paragraph('Account number: 47413608783'))
    d.append(Paragraph('Bank code: 003'))
    d.append(Paragraph('Branch code: 474'))
    d.append(Paragraph('Account location: Hong Kong SAR'))
    d.append(Paragraph(f'Bill To: {email}'))
    if invoice_type == InvoiceTypes.USDT.value:
        d.append(Paragraph('USDT TRC20: TPpj5Zh9UJ2ruR55VyMcfd1GAxL5xezA5Y'))
    elif invoice_type == InvoiceTypes.CAPITALIST.value:
        d.append(Paragraph(f'Capitalist: U13754983'))
    d.append(Spacer(1, 20))
    d.append(Paragraph(f'Subtotal: {amount}. Tax: 0%. Total: {amount}'))
    d.append(Spacer(1, 20))
    d.append(Paragraph('Agatix Story Limited'))
    d.append(Paragraph('UNIT 1603, 16TH FLOOR, THE L. PLAZA 367 - 375 QUEEN\'S ROAD'))
    d.append(Paragraph('CENTRAL SHEUNG WAN HK, Hong Kong,'))
    d.append(Paragraph('Hong Kong, 999077'))
    d.append(Paragraph('SEO: Vishnevetskii Konstantin'))
    return d


class Invoice(models.Model):
    user = models.ForeignKey('platform_main.User', on_delete=models.PROTECT)
    amount = models.IntegerField()
    type = models.CharField(choices=InvoiceTypes.choices)
    paid = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)

    def generate_pdf(self):
        buffer = BytesIO()
        SimpleDocTemplate(buffer, pagesize=A4, rightMargin=12, leftMargin=12, topMargin=12, bottomMargin=6).build(
            build_invoice([], self.id, self.user.email, self.amount, self.type, self.created_at)
        )
        buffer.seek(0)
        return buffer

    def get_status(self) -> tuple:
        if self.paid:
            return 'paid', 'paid'
        return 'wait', 'waiting'

platform_main/models/statistics.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from platform_main.models.campaign import Status

from utils.models import ModelEnhanced


class Statistics(ModelEnhanced):
    date = models.DateField()
    clicks = models.IntegerField(default=0)
    company = models.ForeignKey('platform_main.Campaign', on_delete=models.CASCADE)

templates/v2/admin/header.html
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>

<header class="header">
    <div class="header__container container">
        <a class="header__logo" href="{% url 'platform_main:admin_home' %}">
            <img src="{% static 'images/logo.svg' %}" alt="Логотип" loading="lazy" width="157" height="49">
        </a>
        <nav class="header__nav">
            <ul class="header__list">
                <li class="header__item">
                    <a class="header__link" href="{% url 'platform_main:admin_home' %}"> Home </a>
                </li>
                <li class="header__item">
                    <a class="header__link" href="{% url 'platform_main:admin_total_statistics' %}">
                        Statistics
                    </a>
                </li>
                <li class="header__item">
                    <a class="header__link" href="{% url 'platform_main:admin_campaigns_list' %}">
                        Campaign
                    </a>
                </li>
                <li class="header__item">
                    <a class="header__link" href="{% url 'platform_main:admin_sources_prices' %}">
                        Click prices
                    </a>
                </li>
                <li class="header__item">
                    <a class="header__link" href="{% url 'platform_main:admin_list_invoices' %}">
                        Invoices
                    </a>
                </li>
                <li class="header__item">
                    <a class="header__link" href="{% url 'platform_main:admin_sources_list' %}"> Sources </a>
                </li>
                <li class="header__item">
                    <a class="header__link" href="{% url 'platform_main:admin_accounts_list' %}">
                        Accounts
                    </a>
                </li>
            </ul>
        </nav>

        <div class="header__info">
            <div class="header__user">
                <svg class="sprite header__user-icon" viewBox="0 0 24 24" width="24" height="24">
                    <use href="{% static 'images/sprite.svg' %}#user-shield"></use>
                </svg>
                <div class="header__content">
                    <span id="change-credentials" class="header__name">{{ request.user.name }}</span>
                    {% if len_waiting %}
                    <span class="waiting">{{ len_waiting }}</span>
                    <div class="info_wait"> {{ len_waiting }} campaigns are awaiting confirmation</div>
                    {% endif %}
                    <div class="header__mail small-text">{{ request.user.email}}</div>
                </div>
            </div>

            <!-- if you need to use button just uncomment under code -->
            <!--<button class="header__logout">
              @<svg class="sprite header__logout-icon" viewBox="0 0 24 24" width="24" height="24">
          <use href="img/sprite.svg#logout"></use>
      </svg>
            </button>-->
            <a class="header__logout" href="{% url 'platform_main:logout' %}" aria-label="Logout">
                <svg class="sprite header__logout-icon" viewBox="0 0 24 24" width="24" height="24">
                    <use href="{% static 'images/sprite.svg' %}#logout"></use>
                </svg>
            </a>
        </div>
    </div>
</header>

<div class="modal" data-modal-name="change-credentials" role="alertdialog" aria-labelledby="add-title"
     aria-label="Add new invoice">
    <div class="modal__holder"></div>
    <div class="modal__container">
        <button class="modal__close" aria-label="Close modal">
            <span></span>
            <span></span>
        </button>
        <div class="modal__content">
            <form class="" method="post"
                  id='change-email-password'>
                {% csrf_token %}
                <div class="add-invoice-payments__title title" id="">Change email & password</div>
                <ul class="add-invoice-payments__list">
                    <li class="add-invoice-payments__item">
                        <div class="add-invoice-payments__label">
                            <span class="add-invoice-payments__text">Email</span>


                            <input type="email" class="input" placeholder="Enter a new email" name="email">
                            <div class="email-error-message"></div>
                        </div>
                    </li>
                    <li class="add-modal__li">
                        <span class="add-modal__text">Password:</span>
                        <div class="password-input-wrapper">
                            <input class="input" type="password" placeholder="Enter a new password"
                                   name="new_password" id="password-input" required>
                            <button type="button" class="password-toggle-btn">
                                <i class="fas fa-eye-slash"></i>
                            </button>
                        </div>
                        <div class="password-error-message"></div>
                    </li>
                </ul>
                <button id = 'confirm_button' class="add-invoice-payments__button button button_dark" type="submit">
                    Confirm
                </button>
            </form>
        </div>
    </div>
</div>
<script>
    const password_i = document.getElementById('password-input');
    const passwordToggleBtn = document.querySelector('.password-toggle-btn');
    const passwordToggleIcon = passwordToggleBtn.querySelector('i');

    passwordToggleBtn.addEventListener('click', () => {
        if (password_i.type === 'password') {
            password_i.type = 'text';
            passwordToggleIcon.classList.remove('fa-eye-slash');
            passwordToggleIcon.classList.add('fa-eye');
        } else {
            password_i.type = 'password';
            passwordToggleIcon.classList.remove('fa-eye');
            passwordToggleIcon.classList.add('fa-eye-slash');
        }
    });

    let user_pas = document.getElementById('change-credentials')
    let mod = document.querySelector(`[data-modal-name=${user_pas.getAttribute('id')}]`)
    user_pas.style.cursor = 'pointer'
    user_pas.addEventListener('click', () => {

        document.body.classList.add("scroll-hidden")
        let close_holder = [mod.querySelector('.modal__close'), mod.querySelector('.modal__holder')]
        mod.classList.add('is-open')


        close_holder.forEach((e) => {
            e.addEventListener(('click'), () => {
                mod.classList.remove('is-open')
                document.body.classList.remove("scroll-hidden")
            })
        })
    })

    let change_form = document.getElementById('change-email-password');
    let passwordErrorMessage = document.querySelector('.password-error-message');
    let emailErrorMessage = document.querySelector('.email-error-message');

    function validatePassword() {
        let password = password_i.value;
        let isValid = true;

        // Проверка длины пароля
        if (password.length < 8) {
            passwordErrorMessage.textContent = 'Password must be at least 8 characters long.'
            passwordErrorMessage.classList.add('password-error-change')
            setTimeout(() => {
                passwordErrorMessage.classList.remove('password-error-change')
            }, 500)
            isValid = false;
        }
        // Проверка надежности пароля (наличие букв)
        else if (!/[a-zA-Z]/.test(password)) {
            passwordErrorMessage.textContent = 'Password must contain at least one letter.';
            passwordErrorMessage.classList.add('password-error-change')
            setTimeout(() => {
                passwordErrorMessage.classList.remove('password-error-change')
            }, 500)
            isValid = false;
        } else {
            passwordErrorMessage.textContent = '';
        }


        return isValid;
    }

    change_form.addEventListener("submit", (e) => {
        e.preventDefault();

        if (validatePassword()) {
            const formData = new FormData(e.target);

            fetch('/change_password/', {
                method: 'POST',
                body: formData
            })
                .then(response => response.json())
                .then(data => {
                    if (data.message === 'ok') {
                        let confirm_button = document.getElementById('confirm_button')
                        confirm_button.style.transition = '0.5s'
                        confirm_button.style.backgroundColor = 'green'
                        confirm_button.textContent = 'Success ✓'
                        confirm_button.style.scale = '1.2'
                        confirm_button.style.borderRadius = '20px'
                        setTimeout(()=>{
                            window.location.reload()
                        }, 2000)


                    } else if (data.message === 'email already exist') {
                        emailErrorMessage.textContent = 'Email already exist';
                        emailErrorMessage.classList.add('email-error-change')
                        setTimeout(() => {
                            emailErrorMessage.classList.remove('email-error-change')
                        }, 500)
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                });
        }
    });

</script>

templates/v2/admin/index.html
{% extends 'v2/base.html' %}
{% load static %}

{% block title %}Admin{% endblock %}

{% block links %}

{% endblock %}

{% block content %}
    <main class="main">
        <div class="admin">
            <div class="container">
                <div class="page-head">
                    <div class="big-title">Hello, {{ request.user.name }}!</div>
                </div>
                <div class="admin__board">
                    <ul class="admin__cards">
                        <li class="admin__card admin__card_megaphone">
                            <a href="{% url 'platform_main:admin_campaigns_list' %}" class="admin__link">
                                <div class="admin__wrap">
                                    <div class="admin__text small-title">Campaign</div>
                                    <div class="admin__more">
                                        <svg class="sprite admin__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="admin__card admin__card_price">
                            <a href="{% url 'platform_main:admin_sources_prices' %}" class="admin__link">
                                <div class="admin__wrap">
                                    <div class="admin__text small-title">Click prices</div>
                                    <div class="admin__more">
                                        <svg class="sprite admin__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="admin__card admin__card_earth">
                            <a href="{% url 'platform_main:admin_sources_prices' %}" class="admin__link">
                                <div class="admin__wrap">
                                    <div class="admin__text small-title">Sources</div>
                                    <div class="admin__more">
                                        <svg class="sprite admin__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="admin__card admin__card_graph">
                            <a href="{% url 'platform_main:admin_total_statistics' %}" class="admin__link">
                                <div class="admin__wrap">
                                    <div class="admin__text small-title">Statistics</div>
                                    <div class="admin__more">
                                        <svg class="sprite admin__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="admin__card admin__card_wallet">
                            <a href="{% url 'platform_main:admin_list_invoices' %}" class="admin__link">
                                <div class="admin__wrap">
                                    <div class="admin__text small-title">Invoices</div>
                                    <div class="admin__more">
                                        <svg class="sprite admin__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="admin__card admin__card_account">
                            <a href="{% url 'platform_main:admin_accounts_list' %}" class="admin__link">
                                <div class="admin__wrap">
                                    <div class="admin__text small-title">Accounts</div>
                                    <div class="admin__more">
                                        <svg class="sprite admin__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/v2/admin/login.html
{% extends 'v2/auth/base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block links %}

{% endblock %}

{% block content %}
    <div class="auth">
        <div class="auth__container">
            <div class="auth__logo text-center">
                <img src="{% static "images/pages/auth/auth-logo.svg" %}" alt="Логотип" loading="lazy" width="157"
                     height="49">
            </div>
            <form class="auth__form" action="{% url 'platform_main:admin_login' %}" method="post" novalidate>
                {% csrf_token %}
                <h1 class="auth__title big-title text-center">Login</h1>
                <p>
                    {% if message %}
                        {{ message }}
                    {% endif %}
                </p>
                <input class="auth__input input input_big" type="text" placeholder="Email" name="email">
                <input class="auth__input input input_big" type="password" placeholder="Password" name="password">

                <button class="auth__button button button_yellow" type="submit">sign in</button>
                <!--if you need to use actions form delete link under and uncomented code up-->
                {#                <a class="auth__button button button_yellow" href="user-index.html">sign in</a>#}

                <div class="auth__bottom descr">
                    <div class="auth__bottom-text">No account?</div>
                    <a class="auth__bottom-link" href="{% url 'platform_main:register' %}">Register</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block scripts %}

{% endblock %}