platform_main/urls.py
from django.urls import path
from platform_main.views.user import *
from platform_main.views.admin import *
from platform_main.views.integration import *
from platform_main.views.user.campaigns import get_statistic, get_min_price
from platform_main.views.user.register import ChangePassword
from platform_main.views.user.login import home_redirect

urlpatterns = [
    # User
    path('', home_redirect, name='start'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('home/', HomeView.as_view(), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('campaigns/create/', CreateCampaignView.as_view(), name='campaigns_create'),
    path('campaigns/list/', ListCampaignsView.as_view(), name='campaigns_list'),
    path('campaigns/<int:campaign_id>/statistics', CampaignStatistics.as_view(), name='campaigns_statistics'),
    path('campaigns/<int:pk>/delete', DeleteCampaign.as_view(), name='campaigns_delete'),
    path('campaigns/<int:pk>/update', UpdateCampaign.as_view(), name='campaigns_update'),
    path('campaigns/<int:campaign_id>/<str:action>', CampaignAction.as_view(), name='campaigns_action'),
    path('campaigns/create/get_min_price', get_min_price),
    path('invoices/list', ListInvoices.as_view(), name='user_invoices_list'),
    path('invoices/create', CreateInvoice.as_view(), name='user_invoice_create'),
    path('invoices/download/<int:invoice_id>', DownloadInvoice.as_view(), name='user_invoice_download'),

    path('total_statistics', AllStatistics.as_view(), name='total_statistics'),
    path('get_statistic', get_statistic, name='get_statistic'),
    # Admin
    path('admin/login/', AdminLoginView.as_view(), name='admin_login'),
    path('admin/statistics/', AllStatistics.as_view(), name='admin_total_statistics'),

    # Campaigns
    path('admin/campaigns/<int:campaign_id>/delete/', AdminDeleteCampaignView.as_view(), name='admin_campaign_delete'),
    path('admin/campaigns/list/', AdminCampaignsView.as_view(), name='admin_campaigns_list'),
    path('admin/campaigns/', AdminCreateCampaignView.as_view(), name='admin_campaign_create'),
    path('admin/home/', AdminHomeView.as_view(), name='admin_home'),
    path('admin/campaigns/<int:campaign_id>', AdminCampaign.as_view(), name='admin_campaign'),
    path('admin/campaigns/<int:campaign_id>/update', AdminCampaignUpdate.as_view(), name='admin_campaign_update'),
    path('admin/campaigns/<int:campaign_id>/start',
         AdminCampaignAction.as_view(action="start"),
         name='admin_campaign_action_start'),
    path('admin/campaigns/<int:campaign_id>/stop',
         AdminCampaignAction.as_view(action="stop"),
         name='admin_campaign_action_stop'),

    # Accounts
    path('admin/accounts/list/', AdminAccountsView.as_view(), name='admin_accounts_list'),
    path('admin/accounts/delete/<int:account_id>', AdminDeleteAccountView.as_view(), name='admin_account_delete'),
    path('admin/accounts/<int:account_id>', AdminAccountView.as_view(), name='admin_account'),
    path('admin/accounts/<int:account_id>/stop', AdminStopAccount.as_view(), name='admin_account_stop'),

    # Sources
    path('admin/sources', AdminSourcesView.as_view(), name='admin_sources_list'),
    path('admin/click_prices', AdminSourcesPriceView.as_view(), name='admin_sources_prices'),
    path('admin/sources_prices/create', AdminCreateSourcePrice.as_view(), name='admin_sources_prices_create'),
    path('admin/sources_prices/<int:source_price>/update',
         AdminSourcesUpdate.as_view(),
         name='admin_update_source_price'),
    path('admin/sources_prices/<int:pk>/delete',
         AdminDeleteSourcePrice.as_view(),
         name='admin_delete_source_price'),
    path('admin/sources/create', AdminCreateSource.as_view(), name='admin_create_source'),
    path('admin/sources/<int:pk>/edit', AdminUpdateSource.as_view(), name='admin_update_source'),
    path('admin/sources/<int:pk>/delete', AdminDeleteSource.as_view(), name='admin_delete_source'),

    # Invoices
    path('admin/invoices/<int:pk>/delete', AdminInvoiceDelete.as_view(), name='admin_delete_invoice'),
    path('admin/invoices/<int:pk>/accept', AdminInvoiceAccept.as_view(), name='admin_accept_invoice'),
    path('admin/invoices/list/', AdminListInvoices.as_view(), name='admin_list_invoices'),
    path('admin/invoices/<int:pk>/download', AdminDownloadInvoice.as_view(), name='admin_download_invoice'),

    # Integration
    path('integrations/campaigns', ActiveCampaigns.as_view(), name='integrations_list_campaigns'),
    path('change_password/', ChangePassword.as_view())

]

redirectplatform/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    re_path('', include(('platform_main.urls', 'platform_main'), namespace='platform_main')),
    path('admin/su35', admin.site.urls),
]

platform_main/models/campaign.py
from django.db import models
from django.db.models import OuterRef, F, Sum, ExpressionWrapper, Value, Min
from django.db.models.functions import Coalesce
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.postgres.fields import ArrayField
from django import forms

from platform_main.models.enums import Geo, EmailType, OperationalSystem, Platform, Format
from utils.models import ModelEnhanced


class ChoiceArrayField(ArrayField):
    """
    A field that allows us to store an array of choices.

    Uses Django 1.9's postgres ArrayField
    and a MultipleChoiceField for its formfield.

    Usage:

        choices = ChoiceArrayField(models.CharField(max_length=...,
                                                    choices=(...,)),
                                   default=[...])
    """

    def formfield(self, **kwargs):
        defaults = {
            'form_class': forms.MultipleChoiceField,
            'choices': self.base_field.choices,
        }
        defaults.update(kwargs)
        # Skip our parent's formfield implementation completely as we don't
        # care for it.
        # pylint:disable=bad-super-call
        return super(ArrayField, self).formfield(**defaults)


class Status(models.TextChoices):
    RUNNING = 'running', _('Running')
    STOPPED = 'stopped', _('Stopped')


class FutureStatuses(models.TextChoices):
    REQUEST_STOP = 'stop_requested', _("Stop requested")
    REQUEST_RUN = 'run_requested', _("Run requested")


FutureStatusesMapping = {
    FutureStatuses.REQUEST_STOP.value: Status.STOPPED.value,
    FutureStatuses.REQUEST_RUN.value: Status.RUNNING.value
}


class Source(ModelEnhanced):
    name = models.CharField(max_length=20)
    system_id = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class SourcePrice(ModelEnhanced):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    type = models.CharField(choices=EmailType.choices)
    format = models.CharField(choices=Format.choices)
    platform = models.CharField(choices=Platform.choices)
    geo = models.CharField(choices=Geo.choices)
    price = models.DecimalField(max_digits=10, decimal_places=4)

    @classmethod
    def get_unique_values(cls, filter_data: dict):
        return cls.objects.all().filter(**filter_data) \
            .order_by() \
            .values('source', 'type', 'format', 'platform', 'geo')

    @classmethod
    def get_min_price(cls, filter_data: dict):
        res = cls.objects.all().filter(**filter_data).aggregate(min_price=Min('price'))
        return res.get('min_price', 0)


class CustomCampaignManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)

    def get_sources_statistics(self):
        subquery_utils = {k: OuterRef(k) for k in ['format', 'type', 'geo', 'os', 'platform', 'source']}
        subquery_running = self.get_queryset() \
            .filter(current_status=Status.RUNNING.value, **subquery_utils) \
            .values('format', 'type', 'geo', 'platform', 'source') \
            .annotate(total_clicks=Sum('clicks_per_day', default=0)) \
            .values('total_clicks')
        subquery_waiting_for_moderation = self.get_queryset() \
            .filter(current_status=Status.STOPPED.value, next_status__isnull=False, **subquery_utils) \
            .values('format', 'type', 'geo', 'platform', 'source') \
            .annotate(total_clicks=Sum('clicks_per_day', default=0)) \
            .values('total_clicks')
        res = self.get_queryset().values('format', 'type', 'geo', 'platform', 'source__id', 'source__name') \
            .annotate(current=Coalesce(subquery_running, Value(0))) \
            .annotate(future=Coalesce(subquery_waiting_for_moderation, F('current'))) \
            .annotate(delta=ExpressionWrapper(F('future') - F('current'), output_field=models.IntegerField()))
        res = res.distinct()
        return res


class Campaign(ModelEnhanced):
    name = models.CharField(max_length=250)
    type = models.CharField(choices=EmailType.choices)
    format = models.CharField(choices=Format.choices)
    link = models.CharField(max_length=250)
    platform = models.CharField(choices=Platform.choices)
    os = ChoiceArrayField(base_field=models.CharField(choices=OperationalSystem.choices, max_length=20), null=False)
    geo = models.CharField(choices=Geo.choices)
    price = models.DecimalField(max_digits=10, decimal_places=4)
    # daily_budget = models.IntegerField(null=True)
    clicks_per_day = models.IntegerField()
    user = models.ForeignKey('platform_main.User', on_delete=models.SET_NULL, related_name='campaigns', null=True)
    current_status = models.CharField(choices=Status.choices, default=Status.STOPPED)
    next_status = models.CharField(choices=FutureStatuses.choices, null=True)
    is_deleted = models.BooleanField(default=False)
    source = models.ForeignKey('platform_main.Source', on_delete=models.PROTECT)

    @property
    def os_display(self):
        return ', '.join([str(OperationalSystem(_os).label) for _os in self.os])

    def moderation_decision(self, action: str):
        if action == 'start':
            next_status = Status.RUNNING.value
        elif action == 'stop':
            next_status = Status.STOPPED.value
        else:
            raise Exception
        self.next_status = None
        self.current_status = next_status
        self.save(update_fields=['current_status', 'next_status'])

    def user_action(self, action: FutureStatuses):
        next_status = FutureStatusesMapping.get(action.value)
        if next_status == self.current_status:
            self.next_status = None
            self.save(update_fields=['next_status'])
        else:
            self.next_status = action.value
            self.save(update_fields=['next_status'])

    def delete(self, *args, **kwargs):
        self.is_deleted = True
        self.save(update_fields=['is_deleted'])

    @property
    def get_css_class(self):
        match self.current_status:
            case "running":
                return "start"
            case "stopped":
                return "stop"

    @property
    def get_button_src(self):
        match self.current_status:
            case "running":
                return f"admin/campaigns/stop.svg"
            case "stopped":
                return f"admin/campaigns/start.svg"

    @property
    def clicks_today(self) -> int:
        try:
            clicks = self.clicks_set.all().get(at=timezone.now().replace(minute=0, second=0, microsecond=0))
            return clicks.clicks
        except ObjectDoesNotExist:
            return 0

    objects = CustomCampaignManager()

platform_main/models/statistics.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from platform_main.models.campaign import Status

from utils.models import ModelEnhanced


class Statistics(ModelEnhanced):
    date = models.DateField()
    clicks = models.IntegerField(default=0)
    company = models.ForeignKey('platform_main.Campaign', on_delete=models.CASCADE)

templates/campaigns/create.html
{% extends "authorized_header.html" %}
{% block title %} New campaign {% endblock %}
{% load rest_framework %}
{% block content %}
    <form action="{% url 'platform_main:campaigns_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if not is_final %}
            <p><input type="submit" value="Next"></p>
        {% else %}
            <p><input type="submit" value="Create"></p>
        {% endif %}
    </form>
{% endblock %}

templates/campaigns/edit.html
{% extends "authorized_header.html" %}
{% load static %}
{% block title %} My campaigns {% endblock %}
{% block scripts %}
    <link rel="stylesheet" href={% static 'css/list_campaigns.css' %}>
{% endblock %}
{% block content %}
    <form action="{% url 'platform_main:campaigns_update' object.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Save"></p>
        <a href={% url 'platform_main:campaigns_list' %}>Back to campaigns list</a>
    </form>
{% endblock %}

templates/campaigns/list.html
{% extends "authorized_header.html" %}
{% load static %}
{% block title %} My campaigns {% endblock %}
{% block scripts %}
    <link rel="stylesheet" href={% static 'css/list_campaigns.css' %}>
{% endblock %}
{% block content %}
    <a href="/campaigns/create">Create new campaign</a>
    {% if campaigns %}
        <table class="mainTable" border="1" bordercolor="black" cellspacing="0">
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Daily clicks</td>
                <td>Clicks today</td>
                <td>Type</td>
                <td>Format</td>
                <td>Platform</td>
                <td>OS</td>
                <td>Geo</td>
                <td>Price</td>
                <td>Status</td>
                <td>Statistics</td>
            </tr>
            {% for campaign in campaigns %}
                <tr>
                    <td>{{ campaign.id }}</td>
                    <td>{{ campaign.name }}</td>
                    <td>{{ campaign.clicks_per_day }}</td>
                    <td>{{ campaign.clicks_today }}</td>
                    <td>{{ campaign.get_type_display }}</td>
                    <td>{{ campaign.get_format_display }}</td>
                    <td>{{ campaign.get_platform_display }}</td>
                    <td>{{ campaign.os_display }}</td>
                    <td>{{ campaign.get_geo_display }}</td>
                    <td>{{ campaign.price }}</td>
                    <td>
                        {% if campaign.next_status %}
                            {{ campaign.current_status }} ({{ campaign.next_status }})
                        {% else %}
                            {{ campaign.current_status }}
                        {% endif %}
                        {% if campaign.current_status == "running" or campaign.next_status == "run_requested" %}
                            <form method="post" action="../{{ campaign.id }}/stop_requested">
                                {% csrf_token %}
                                <input type="submit" value="Stop">
                            </form>
                        {% elif  campaign.current_status == "stopped" or campaign.next_status == "stop_requested" %}
                            <form method="post" action="../{{ campaign.id }}/run_requested">
                                {% csrf_token %}
                                <input type="submit" value="Run">
                            </form>
                        {% endif %}
                        {% if campaign.current_status == "stopped" %}
                            <form method="post" action="{% url 'platform_main:campaigns_delete' campaign.id %}">
                                {% csrf_token %}
                                <input type="submit" value="Delete">
                            </form>
                            <form method="get" action="{% url 'platform_main:campaigns_update' campaign.id %}">
                                <input type="submit" value="Update">
                            </form>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'platform_main:campaigns_statistics' campaign.id %}">
                            <button>
                                Show statistics
                            </button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no campaigns.</p>
    {% endif %}
{% endblock %}

templates/campaigns/statistics.html
{% extends "authorized_header.html" %}
{% block title %} New campaign {% endblock %}
{% load rest_framework %}
{% block content %}
    <a href="{% url 'platform_main:campaigns_list' %}">
        <button>Back to campaign</button>
    </a>
    <div class="settings">
        <form action="{% url 'platform_main:campaigns_statistics' campaign_id %}" method="get">
            <label for="selectStatisticsBy">Statistics by</label>
            <select name="statistics_by" id="selectStatisticsBy">
                <option>All Time</option>
                <option>Last Month</option>
                <option>Current Month</option>
                <option>Last 30 Days</option>
                <option>Today</option>
                <option>Yesterday</option>
            </select>
            <button type="submit">Filter</button>
        </form>
    </div>
    <table class="mainTable" border="1" bordercolor="black" cellspacing="0">
        <tr>
            <th>Date</th>
            <th>Clicks</th>
            <th>Total amount</th>
        </tr>
        {% for click in clicks %}
            <tr>
                <th>{{ click.at }}</th>
                <th>{{ click.clicks }}</th>
                <th>{{ click.amount }}$</th>
            </tr>
        {% endfor %}
    </table>
{% endblock %}