platform_main/urls.py
from django.urls import path
from platform_main.views.user import *
from platform_main.views.admin import *
from platform_main.views.integration import *
from platform_main.views.user.campaigns import get_statistic, get_min_price
from platform_main.views.user.register import ChangePassword
from platform_main.views.user.login import home_redirect

urlpatterns = [
    # User
    path('', home_redirect, name='start'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('home/', HomeView.as_view(), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('campaigns/create/', CreateCampaignView.as_view(), name='campaigns_create'),
    path('campaigns/list/', ListCampaignsView.as_view(), name='campaigns_list'),
    path('campaigns/<int:campaign_id>/statistics', CampaignStatistics.as_view(), name='campaigns_statistics'),
    path('campaigns/<int:pk>/delete', DeleteCampaign.as_view(), name='campaigns_delete'),
    path('campaigns/<int:pk>/update', UpdateCampaign.as_view(), name='campaigns_update'),
    path('campaigns/<int:campaign_id>/<str:action>', CampaignAction.as_view(), name='campaigns_action'),
    path('campaigns/create/get_min_price', get_min_price),
    path('invoices/list', ListInvoices.as_view(), name='user_invoices_list'),
    path('invoices/create', CreateInvoice.as_view(), name='user_invoice_create'),
    path('invoices/download/<int:invoice_id>', DownloadInvoice.as_view(), name='user_invoice_download'),

    path('total_statistics', AllStatistics.as_view(), name='total_statistics'),
    path('get_statistic', get_statistic, name='get_statistic'),
    # Admin
    path('admin/login/', AdminLoginView.as_view(), name='admin_login'),
    path('admin/statistics/', AllStatistics.as_view(), name='admin_total_statistics'),

    # Campaigns
    path('admin/campaigns/<int:campaign_id>/delete/', AdminDeleteCampaignView.as_view(), name='admin_campaign_delete'),
    path('admin/campaigns/list/', AdminCampaignsView.as_view(), name='admin_campaigns_list'),
    path('admin/campaigns/', AdminCreateCampaignView.as_view(), name='admin_campaign_create'),
    path('admin/home/', AdminHomeView.as_view(), name='admin_home'),
    path('admin/campaigns/<int:campaign_id>', AdminCampaign.as_view(), name='admin_campaign'),
    path('admin/campaigns/<int:campaign_id>/update', AdminCampaignUpdate.as_view(), name='admin_campaign_update'),
    path('admin/campaigns/<int:campaign_id>/start',
         AdminCampaignAction.as_view(action="start"),
         name='admin_campaign_action_start'),
    path('admin/campaigns/<int:campaign_id>/stop',
         AdminCampaignAction.as_view(action="stop"),
         name='admin_campaign_action_stop'),

    # Accounts
    path('admin/accounts/list/', AdminAccountsView.as_view(), name='admin_accounts_list'),
    path('admin/accounts/delete/<int:account_id>', AdminDeleteAccountView.as_view(), name='admin_account_delete'),
    path('admin/accounts/<int:account_id>', AdminAccountView.as_view(), name='admin_account'),
    path('admin/accounts/<int:account_id>/stop', AdminStopAccount.as_view(), name='admin_account_stop'),

    # Sources
    path('admin/sources', AdminSourcesView.as_view(), name='admin_sources_list'),
    path('admin/click_prices', AdminSourcesPriceView.as_view(), name='admin_sources_prices'),
    path('admin/sources_prices/create', AdminCreateSourcePrice.as_view(), name='admin_sources_prices_create'),
    path('admin/sources_prices/<int:source_price>/update',
         AdminSourcesUpdate.as_view(),
         name='admin_update_source_price'),
    path('admin/sources_prices/<int:pk>/delete',
         AdminDeleteSourcePrice.as_view(),
         name='admin_delete_source_price'),
    path('admin/sources/create', AdminCreateSource.as_view(), name='admin_create_source'),
    path('admin/sources/<int:pk>/edit', AdminUpdateSource.as_view(), name='admin_update_source'),
    path('admin/sources/<int:pk>/delete', AdminDeleteSource.as_view(), name='admin_delete_source'),

    # Invoices
    path('admin/invoices/<int:pk>/delete', AdminInvoiceDelete.as_view(), name='admin_delete_invoice'),
    path('admin/invoices/<int:pk>/accept', AdminInvoiceAccept.as_view(), name='admin_accept_invoice'),
    path('admin/invoices/list/', AdminListInvoices.as_view(), name='admin_list_invoices'),
    path('admin/invoices/<int:pk>/download', AdminDownloadInvoice.as_view(), name='admin_download_invoice'),

    # Integration
    path('integrations/campaigns', ActiveCampaigns.as_view(), name='integrations_list_campaigns'),
    path('change_password/', ChangePassword.as_view())

]

redirectplatform/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    re_path('', include(('platform_main.urls', 'platform_main'), namespace='platform_main')),
    path('admin/su35', admin.site.urls),
]

platform_main/models/campaign.py
from django.db import models
from django.db.models import OuterRef, F, Sum, ExpressionWrapper, Value, Min
from django.db.models.functions import Coalesce
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.postgres.fields import ArrayField
from django import forms

from platform_main.models.enums import Geo, EmailType, OperationalSystem, Platform, Format
from utils.models import ModelEnhanced


class ChoiceArrayField(ArrayField):
    """
    A field that allows us to store an array of choices.

    Uses Django 1.9's postgres ArrayField
    and a MultipleChoiceField for its formfield.

    Usage:

        choices = ChoiceArrayField(models.CharField(max_length=...,
                                                    choices=(...,)),
                                   default=[...])
    """

    def formfield(self, **kwargs):
        defaults = {
            'form_class': forms.MultipleChoiceField,
            'choices': self.base_field.choices,
        }
        defaults.update(kwargs)
        # Skip our parent's formfield implementation completely as we don't
        # care for it.
        # pylint:disable=bad-super-call
        return super(ArrayField, self).formfield(**defaults)


class Status(models.TextChoices):
    RUNNING = 'running', _('Running')
    STOPPED = 'stopped', _('Stopped')


class FutureStatuses(models.TextChoices):
    REQUEST_STOP = 'stop_requested', _("Stop requested")
    REQUEST_RUN = 'run_requested', _("Run requested")


FutureStatusesMapping = {
    FutureStatuses.REQUEST_STOP.value: Status.STOPPED.value,
    FutureStatuses.REQUEST_RUN.value: Status.RUNNING.value
}


class Source(ModelEnhanced):
    name = models.CharField(max_length=20)
    system_id = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class SourcePrice(ModelEnhanced):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    type = models.CharField(choices=EmailType.choices)
    format = models.CharField(choices=Format.choices)
    platform = models.CharField(choices=Platform.choices)
    geo = models.CharField(choices=Geo.choices)
    price = models.DecimalField(max_digits=10, decimal_places=4)

    @classmethod
    def get_unique_values(cls, filter_data: dict):
        return cls.objects.all().filter(**filter_data) \
            .order_by() \
            .values('source', 'type', 'format', 'platform', 'geo')

    @classmethod
    def get_min_price(cls, filter_data: dict):
        res = cls.objects.all().filter(**filter_data).aggregate(min_price=Min('price'))
        return res.get('min_price', 0)


class CustomCampaignManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)

    def get_sources_statistics(self):
        subquery_utils = {k: OuterRef(k) for k in ['format', 'type', 'geo', 'os', 'platform', 'source']}
        subquery_running = self.get_queryset() \
            .filter(current_status=Status.RUNNING.value, **subquery_utils) \
            .values('format', 'type', 'geo', 'platform', 'source') \
            .annotate(total_clicks=Sum('clicks_per_day', default=0)) \
            .values('total_clicks')
        subquery_waiting_for_moderation = self.get_queryset() \
            .filter(current_status=Status.STOPPED.value, next_status__isnull=False, **subquery_utils) \
            .values('format', 'type', 'geo', 'platform', 'source') \
            .annotate(total_clicks=Sum('clicks_per_day', default=0)) \
            .values('total_clicks')
        res = self.get_queryset().values('format', 'type', 'geo', 'platform', 'source__id', 'source__name') \
            .annotate(current=Coalesce(subquery_running, Value(0))) \
            .annotate(future=Coalesce(subquery_waiting_for_moderation, F('current'))) \
            .annotate(delta=ExpressionWrapper(F('future') - F('current'), output_field=models.IntegerField()))
        res = res.distinct()
        return res


class Campaign(ModelEnhanced):
    name = models.CharField(max_length=250)
    type = models.CharField(choices=EmailType.choices)
    format = models.CharField(choices=Format.choices)
    link = models.CharField(max_length=250)
    platform = models.CharField(choices=Platform.choices)
    os = ChoiceArrayField(base_field=models.CharField(choices=OperationalSystem.choices, max_length=20), null=False)
    geo = models.CharField(choices=Geo.choices)
    price = models.DecimalField(max_digits=10, decimal_places=4)
    # daily_budget = models.IntegerField(null=True)
    clicks_per_day = models.IntegerField()
    user = models.ForeignKey('platform_main.User', on_delete=models.SET_NULL, related_name='campaigns', null=True)
    current_status = models.CharField(choices=Status.choices, default=Status.STOPPED)
    next_status = models.CharField(choices=FutureStatuses.choices, null=True)
    is_deleted = models.BooleanField(default=False)
    source = models.ForeignKey('platform_main.Source', on_delete=models.PROTECT)

    @property
    def os_display(self):
        return ', '.join([str(OperationalSystem(_os).label) for _os in self.os])

    def moderation_decision(self, action: str):
        if action == 'start':
            next_status = Status.RUNNING.value
        elif action == 'stop':
            next_status = Status.STOPPED.value
        else:
            raise Exception
        self.next_status = None
        self.current_status = next_status
        self.save(update_fields=['current_status', 'next_status'])

    def user_action(self, action: FutureStatuses):
        next_status = FutureStatusesMapping.get(action.value)
        if next_status == self.current_status:
            self.next_status = None
            self.save(update_fields=['next_status'])
        else:
            self.next_status = action.value
            self.save(update_fields=['next_status'])

    def delete(self, *args, **kwargs):
        self.is_deleted = True
        self.save(update_fields=['is_deleted'])

    @property
    def get_css_class(self):
        match self.current_status:
            case "running":
                return "start"
            case "stopped":
                return "stop"

    @property
    def get_button_src(self):
        match self.current_status:
            case "running":
                return f"admin/campaigns/stop.svg"
            case "stopped":
                return f"admin/campaigns/start.svg"

    @property
    def clicks_today(self) -> int:
        try:
            clicks = self.clicks_set.all().get(at=timezone.now().replace(minute=0, second=0, microsecond=0))
            return clicks.clicks
        except ObjectDoesNotExist:
            return 0

    objects = CustomCampaignManager()

platform_main/models/statistics.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from platform_main.models.campaign import Status

from utils.models import ModelEnhanced


class Statistics(ModelEnhanced):
    date = models.DateField()
    clicks = models.IntegerField(default=0)
    company = models.ForeignKey('platform_main.Campaign', on_delete=models.CASCADE)

platform_main/models/user.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from platform_main.models.campaign import Status, FutureStatuses

from utils.models import ModelEnhanced


class CustomUserManager(UserManager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


class User(ModelEnhanced, AbstractBaseUser, PermissionsMixin):
    email = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100, unique=True)
    manager = models.ForeignKey('platform_main.User', null=True, on_delete=models.SET_NULL)
    company = models.CharField(max_length=255, null=True, blank=True)
    balance = models.DecimalField(max_digits=10, decimal_places=4, default=0)
    is_deleted = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    is_stopped = models.BooleanField(default=False)
    allow_zero_balance = models.BooleanField(default=False)

    objects = CustomUserManager()

    def edit_balance(self, delta):
        self.balance += delta
        self.save(update_fields=['balance'])

    @property
    def clicks_per_day_total(self):
        campaigns = self.campaigns.all().filter(is_deleted=False, current_status=Status.RUNNING.value)
        return sum([c.clicks_per_day for c in campaigns])

    @property
    def is_staff(self):
        return self.is_admin

    @classmethod
    def create_user(cls, email: str, password: str, name: str = None):
        user = cls(email=email)
        if name is not None:
            user.name = name
        user.set_password(password)
        user.save()
        user.refresh_from_db()
        return user

    @property
    def pretty_balance(self):
        full = str(self.balance).split('.')
        first = full[0]
        second = full[1]
        result = first + '.' + second[:2]
        return result

    def stop(self):
        self.is_stopped = not self.is_stopped
        self.save(update_fields=['is_stopped'])
        if self.is_stopped:
            running_campaigns = self.campaigns.all().filter(current_status=Status.RUNNING.value)
            stopped_campaigns = self.campaigns.all().filter(next_status__isnull=False)
            running_campaigns.update(current_status=Status.STOPPED.value, next_status=FutureStatuses.REQUEST_RUN.value)
            stopped_campaigns.update(current_status=Status.STOPPED.value, next_status=None)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def delete(self, *args, **kwargs):
        self.is_deleted = True
        self.campaigns.all().update(is_deleted=True)
        self.save(update_fields=['is_deleted'])

    def is_admin_or_manager(self):
        return self.is_admin or self.is_manager

templates/v2/user/index.html
{% extends 'v2/base.html' %}
{% load static %}

{% block title %}User{% endblock %}

{% block links %}

{% endblock %}

{% block content %}
    <main class="main">
        <div class="user">
            <div class="container">
                <div class="page-head">
                    <div class="big-title">Hello, {{ name }}!</div>
                </div>
                <div class="user__board">
                    <ul class="user__cards">
                        <li class="user__card user__card_megaphone">
                            <a href="{% url 'platform_main:campaigns_list' %}" class="user__link">
                                <div class="user__wrap">
                                    <div class="user__text small-title">Campaign</div>
                                    <div class="user__more">
                                        <svg class="sprite user__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="user__card user__card_headphone">
                            <a href="https://t.me/s/AGATIX_SUPPORT" class="user__link" target="_blank">
                                <div class="user__wrap">
                                    <div class="user__text small-title">Support</div>
                                    <div class="user__more">
                                        <svg class="sprite user__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="user__card user__card_graph">
                            <a href="{% url 'platform_main:total_statistics' %}" class="user__link">
                                <div class="user__wrap">
                                    <div class="user__text small-title">Statistics</div>
                                    <div class="user__more">
                                        <svg class="sprite user__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="user__card user__card_wallet">
                            <a href="{% url 'platform_main:user_invoices_list' %}" class="user__link">
                                <div class="user__wrap">
                                    <div class="user__text small-title">Payments</div>
                                    <div class="user__more">
                                        <svg class="sprite user__icon" viewBox="0 0 24 24" width="24" height="24">
                                            <use href="{% static 'images/sprite.svg' %}#arrow"></use>
                                        </svg>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/v2/user/payments.html
{% extends 'v2/base.html' %}
{% load static %}

{% block title %}Campaigns{% endblock %}

{% block links %}

{% endblock %}

{% block content %}
    <main class="main">
        <div class="main__wrapper">
            <div class="main__container container">
                <div class="page-head">
                    <div class="big-title">Payments</div>
                    <button class="button button_transparent" data-modal-id="add-invoice-payments">
                        <svg class="sprite table__filter-icon" viewBox="0 0 24 24" width="24" height="24">
                            <use href="{% static 'images/sprite.svg' %}#plus"></use>
                        </svg>
                        new invoice
                    </button>
                </div>
                <div class="table__outer">
                    <table class="user-payments__table">
                        <thead>
                        <tr>
                            <td>ID</td>
                            <td>Amount</td>
                            <td>Type</td>
                            <td>Status</td>
                            <td>PDF</td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for invoice in invoices %}
                            <tr>
                                <td>{{ invoice.id }}</td>
                                <td>{{ invoice.amount }}</td>
                                <td>{{ invoice.get_type_display }}</td>
                                <td>
                                    <div class="admin-invoices__td-status admin-invoices__td-status_{{ invoice.get_status.0 }}">{{ invoice.get_status.1 }}</div>
                                    {#                                    <div class="user-payments__td-status user-payments__td-status_wait">{{ invoice.get_status.1 }}</div>#}
                                </td>
                                <td>

                                    <a class="button-download @class"
                                       href="{% url 'platform_main:user_invoice_download' invoice.id %}" download>
                                        <svg class="sprite button-download__icon" viewBox="0 0 24 25" width="24"
                                             height="25">
                                            <use href="{% static 'images/sprite.svg' %}#download"></use>
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="pagination__footer">
                    <div class="pagination__pages">
                        <button class="pagination__page-arrow pagination__page-prev" aria-label="prev page">
                            <svg class="sprite pagination__page-icon" viewBox="0 0 24 24" width="24" height="24">
                                <use href="{% static 'images/sprite.svg' %}#small-arrow"></use>
                            </svg>
                        </button>
                        <div class="pagination__page">
                            Page 1
                        </div>
                        <button class="pagination__page-arrow pagination__page-next" aria-label="next page">
                            <svg class="sprite pagination__page-icon" viewBox="0 0 24 24" width="24" height="24">
                                <use href="{% static 'images/sprite.svg' %}#small-arrow"></use>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <div class="modal" data-modal-name="add-invoice-payments" role="alertdialog" aria-labelledby="add-title"
         aria-label="Add new invoice">
        <div class="modal__holder"></div>
        <div class="modal__container">
            <button class="modal__close" aria-label="Close modal">
                <span></span>
                <span></span>
            </button>
            <div class="modal__content">
                <form class="add-invoice-payments__box" method="post"
                      action="{% url 'platform_main:user_invoice_create' %}" name="form_new_invoice">
                    {% csrf_token %}
                    <div class="add-invoice-payments__title title" id="add-title">Add new invoice</div>
                    <ul class="add-invoice-payments__list">
                        <li class="add-invoice-payments__item">
                            <div class="add-invoice-payments__label">
                                <span class="add-invoice-payments__text">Amount</span>
                                <span class="number">
    <button class="number-plus" type="button" aria-label="plus"
            onclick="this.nextElementSibling.stepUp(); this.nextElementSibling.onchange();"></button>
    <input type="number" min="0" value="0" placeholder="0" name="amount">
    <button class="number-minus" type="button" aria-label="minus"
            onclick="this.previousElementSibling.stepDown(); this.previousElementSibling.onchange();"></button>
</span>
                            </div>
                        </li>
                        <li class="add-modal__li">
                            <label class="add-modal__label" id="user-payments-type">
                                <span class="add-modal__text">Type:</span>
                            </label>
                        </li>
                    </ul>
                    <button class="add-invoice-payments__button button button_dark" type="submit">
                        add
                    </button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    <script>
        payType = [
            {% for type in type_choices %}
                {
                    name: '{{ type.1 }}',
                    value: '{{ type.0 }}',
                },
            {% endfor %}
        ]
        if (userTypeInvoceSelect) {
            _userTypeInvoceSelect = new Treeselect({
                parentHtmlContainer: userTypeInvoceSelect,
                value: '',
                options: payType,
                isSingleSelect: true,
                direction: 'bottom',
                clearable: false,
                searchable: false,
                placeholder: 'Select',
            })
        }
    </script>
    <script src="{% static 'js/user.js' %}"></script>
{% endblock %}

templates/v2/user/statistics.html
{% extends 'v2/base.html' %}
{% load static %}

{% block title %}Campaigns{% endblock %}

{% block links %}

{% endblock %}

{% block content %}
    <main class="main">
        <div class="main__wrapper">
            <div class="container">
                <div class="page-head">
                    <div class="big-title">Statistics</div>
                </div>

                <ul class="tabs list-reset">
                    <li class="tab">
                        <form action="{% url 'platform_main:campaigns_statistics' campaign_id %}" method="get">
                            <button class="tab__button {% if request.GET.statistics_by == "Today" %}tab__button_active{% endif %}"
                                    data-date="Today" name="statistics_by" value="Today">Today
                            </button>
                        </form>
                    </li>
                    <li class="tab">
                        <form action="{% url 'platform_main:campaigns_statistics' campaign_id %}" method="get">
                            <button class="tab__button {% if request.GET.statistics_by == "Yesterday" %}tab__button_active{% endif %}"
                                    data-date="Yesterday" name="statistics_by" value="Yesterday">Yesterday
                            </button>
                        </form>
                    </li>
                    <li class="tab">
                        <form action="{% url 'platform_main:campaigns_statistics' campaign_id %}" method="get">
                            <button class="tab__button {% if request.GET.statistics_by == "Current week" %}tab__button_active{% endif %}"
                                    data-date="Current week" name="statistics_by" value="Current week">Current week
                            </button>
                        </form>
                    </li>
                    <li class="tab">
                        <form action="{% url 'platform_main:campaigns_statistics' campaign_id %}" method="get">
                            <button class="tab__button {% if request.GET.statistics_by == "Last week" %}tab__button_active{% endif %}"
                                    data-date="Last week" name="statistics_by" value="Last week">Last week
                            </button>
                        </form>
                    </li>
                    <li class="tab">
                        <form action="{% url 'platform_main:campaigns_statistics' campaign_id %}" method="get">
                            <button class="tab__button {% if request.GET.statistics_by == "Current month" %}tab__button_active{% endif %}"
                                    data-date="Current month" name="statistics_by" value="Current month">Current month
                            </button>
                        </form>
                    </li>
                    <li class="tab">
                        <form action="{% url 'platform_main:campaigns_statistics' campaign_id %}" method="get">
                            <button class="tab__button {% if request.GET.statistics_by == "Last month" %}tab__button_active{% endif %}"
                                    data-date="Last month" name="statistics_by" value="Last month">Last month
                            </button>
                        </form>
                    </li>
                </ul>

                <div class="statistics__total">
                    <div class="statistics__total-title small-title">Total: {{ total_clicks}} clicks</div>
                    <div class="statistics__total-text">Spent:
                        <div class="statistics__total-balance">${{ total_amount }}</div>
                    </div>
                </div>

                <div class="statistics__chart">
                    <canvas class="statistics__graph" id="statistics-chart-2" aria-label="Chart" role="img"></canvas>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script>
    <script>
        let userChartGlobal;
        let userChart = document.getElementById('statistics-chart-2');
        if (userChart) {
            userChartGlobal = new Chart(userChart, {
                type: 'bar',
                data: {
                    labels: [{% for click in clicks %} "{{ click.at|date:'j/M/Y' }}",{% endfor %}],
                    datasets: [{
                        label: 'clicks',
                        backgroundColor: "#ffe100",
                        borderRadius: 20,
                        maxBarThickness: function (context) {
                            return context.dataset.data.length === 1 ? 300 : undefined;
                        },
                        data: [{% for click in clicks %} {{ click.clicks }},{% endfor %}]
                    },]
                },
                options: {
                    plugins: {
                        legend: {
                            display: false
                        }
                    },
                    scales: {
                        x: {
                            grid: {
                                display: false
                            },
                            stacked: true
                        },
                        y: {
                            grid: {
                                display: false
                            },
                            beginAtZero: true
                        }
                    }
                }
            });
        }
    </script>
{% endblock %}