platform_main/urls.py
from django.urls import path
from platform_main.views.user import *
from platform_main.views.admin import *
from platform_main.views.integration import *
from platform_main.views.user.campaigns import get_statistic, get_min_price
from platform_main.views.user.register import ChangePassword
from platform_main.views.user.login import home_redirect

urlpatterns = [
    # User
    path('', home_redirect, name='start'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('home/', HomeView.as_view(), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('campaigns/create/', CreateCampaignView.as_view(), name='campaigns_create'),
    path('campaigns/list/', ListCampaignsView.as_view(), name='campaigns_list'),
    path('campaigns/<int:campaign_id>/statistics', CampaignStatistics.as_view(), name='campaigns_statistics'),
    path('campaigns/<int:pk>/delete', DeleteCampaign.as_view(), name='campaigns_delete'),
    path('campaigns/<int:pk>/update', UpdateCampaign.as_view(), name='campaigns_update'),
    path('campaigns/<int:campaign_id>/<str:action>', CampaignAction.as_view(), name='campaigns_action'),
    path('campaigns/create/get_min_price', get_min_price),
    path('invoices/list', ListInvoices.as_view(), name='user_invoices_list'),
    path('invoices/create', CreateInvoice.as_view(), name='user_invoice_create'),
    path('invoices/download/<int:invoice_id>', DownloadInvoice.as_view(), name='user_invoice_download'),

    path('total_statistics', AllStatistics.as_view(), name='total_statistics'),
    path('get_statistic', get_statistic, name='get_statistic'),
    # Admin
    path('admin/login/', AdminLoginView.as_view(), name='admin_login'),
    path('admin/statistics/', AllStatistics.as_view(), name='admin_total_statistics'),

    # Campaigns
    path('admin/campaigns/<int:campaign_id>/delete/', AdminDeleteCampaignView.as_view(), name='admin_campaign_delete'),
    path('admin/campaigns/list/', AdminCampaignsView.as_view(), name='admin_campaigns_list'),
    path('admin/campaigns/', AdminCreateCampaignView.as_view(), name='admin_campaign_create'),
    path('admin/home/', AdminHomeView.as_view(), name='admin_home'),
    path('admin/campaigns/<int:campaign_id>', AdminCampaign.as_view(), name='admin_campaign'),
    path('admin/campaigns/<int:campaign_id>/update', AdminCampaignUpdate.as_view(), name='admin_campaign_update'),
    path('admin/campaigns/<int:campaign_id>/start',
         AdminCampaignAction.as_view(action="start"),
         name='admin_campaign_action_start'),
    path('admin/campaigns/<int:campaign_id>/stop',
         AdminCampaignAction.as_view(action="stop"),
         name='admin_campaign_action_stop'),

    # Accounts
    path('admin/accounts/list/', AdminAccountsView.as_view(), name='admin_accounts_list'),
    path('admin/accounts/delete/<int:account_id>', AdminDeleteAccountView.as_view(), name='admin_account_delete'),
    path('admin/accounts/<int:account_id>', AdminAccountView.as_view(), name='admin_account'),
    path('admin/accounts/<int:account_id>/stop', AdminStopAccount.as_view(), name='admin_account_stop'),

    # Sources
    path('admin/sources', AdminSourcesView.as_view(), name='admin_sources_list'),
    path('admin/click_prices', AdminSourcesPriceView.as_view(), name='admin_sources_prices'),
    path('admin/sources_prices/create', AdminCreateSourcePrice.as_view(), name='admin_sources_prices_create'),
    path('admin/sources_prices/<int:source_price>/update',
         AdminSourcesUpdate.as_view(),
         name='admin_update_source_price'),
    path('admin/sources_prices/<int:pk>/delete',
         AdminDeleteSourcePrice.as_view(),
         name='admin_delete_source_price'),
    path('admin/sources/create', AdminCreateSource.as_view(), name='admin_create_source'),
    path('admin/sources/<int:pk>/edit', AdminUpdateSource.as_view(), name='admin_update_source'),
    path('admin/sources/<int:pk>/delete', AdminDeleteSource.as_view(), name='admin_delete_source'),

    # Invoices
    path('admin/invoices/<int:pk>/delete', AdminInvoiceDelete.as_view(), name='admin_delete_invoice'),
    path('admin/invoices/<int:pk>/accept', AdminInvoiceAccept.as_view(), name='admin_accept_invoice'),
    path('admin/invoices/list/', AdminListInvoices.as_view(), name='admin_list_invoices'),
    path('admin/invoices/<int:pk>/download', AdminDownloadInvoice.as_view(), name='admin_download_invoice'),

    # Integration
    path('integrations/campaigns', ActiveCampaigns.as_view(), name='integrations_list_campaigns'),
    path('change_password/', ChangePassword.as_view())

]

redirectplatform/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    re_path('', include(('platform_main.urls', 'platform_main'), namespace='platform_main')),
    path('admin/su35', admin.site.urls),
]

templates/admin_authorized_header.html
{% load rest_framework %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/admin/campaigns/admin_authorized_header.css">
    {% block styles %}{% endblock %}
    <title>
        {% block title %} Base {% endblock %}
    </title>
</head>
{% block scripts %}{% endblock %}
<header class="header">
    <div class="logo"></div>
    <nav class="navigation">
        <ul class="menu">
            <li><a href="{% url 'platform_main:admin_total_statistics' %}">Clicks</a></li>
            <li><a href="{% url 'platform_main:admin_accounts_list' %}">Accounts</a></li>
            <li><a href="{% url 'platform_main:admin_sources_list' %}">Sources</a></li>
            <li><a href="{% url 'platform_main:admin_sources_prices' %}">Click prices</a></li>
            <li><a href="{% url 'platform_main:admin_campaigns_list' %}">Campaigns</a></li>
            <li><a href="{% url 'platform_main:admin_list_invoices' %}">Invoices</a></li>
        </ul>
    </nav>
    <div class="user-info">
    </div>
</header>
{% block content %}
{% endblock %}

templates/authorized_header.html
{% load rest_framework %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/authorized_header.css">
    <title>
        {% block title %} Base {% endblock %}
    </title>
</head>
{% block scripts %}{% endblock %}
<header class="header">
    <div class="logo"></div>
    <nav class="navigation">
        <ul class="menu">
            <li><a href="/total_statistics">Statistics</a></li>
            <li><a href="/campaigns/list">Campaigns</a></li>
            <li><a href="{% url 'platform_main:user_invoices_list' %}">Invoices</a></li>
        </ul>
    </nav>
    <div class="user-info">
        {% if user %}
            <span class="balance">Balance: ${{ user.balance }}</span>
            <a href="/home">
                <span class="username">{{ user.email }}</span>
            </a>
            <form action="{% url 'platform_main:logout' %}" method="post">
                {% csrf_token %}
                <button>Logout</button>
            </form>
        {% endif %}
    </div>
</header>
{% block content %}
{% endblock %}

templates/total_statistics.html
{% extends "authorized_header.html" %}
{% block title %} All campaigns statistics {% endblock %}
{% load rest_framework %}
{% block content %}
    <div class="settings">
        <form action="{% url 'platform_main:total_statistics' %}" method="get">
            <label for="selectStatisticsBy">Statistics by</label>
            <select name="statistics_by" id="selectStatisticsBy">
                <option>All Time</option>
                <option>Last Month</option>
                <option>Current Month</option>
                <option>Last 30 Days</option>
                <option>Today</option>
                <option>Yesterday</option>
            </select>
            <button type="submit">Filter</button>
        </form>
    </div>
    <table class="mainTable" border="1" bordercolor="black" cellspacing="0">
        <tr>
            <th>Date</th>
            <th>Clicks</th>
            <th>Total amount</th>
        </tr>
        {% for click in clicks %}
            <tr>
                <th>{{ click.at }}</th>
                <th>{{ click.clicks }}</th>
                <th>{{ click.amount }}$</th>
            </tr>
        {% endfor %}
    </table>

{% endblock %}